apiVersion: v1
kind: Service
metadata:
  name: flask-app-k8s
  namespace: development
  labels:
    app: flask-app-k8s
spec:
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    app: flask-app-k8s
