apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_app_k8s
  namespace: development
  labels:
    app: flask_app_k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask_app_k8s
  template:
    metadata:
      labels:
        app: flask_app_k8s
    spec:
      containers:
        - name: flask_app_k8s
          image: tatendaz/flask_app_k8s:latest
          ports:
            - containerPort: 8000
              name: http