apiVersion: v1
kind: Service
metadata:
  name: flask_app_k8s
  namespace: development
  labels:
    app: flask_app_k8s
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    app: flask_app_k8s