on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: flask_app_k8s
  CONTAINER_NAME: flask_app_k8s
  DEPLOYMENT_NAME: flask_app_k8s

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run:
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 b44ab5f5-143a-4486-af43-9edcaa1ef0bc
          # Deploy Docker image to the DigitalOcean kubernetes cluster
      - name: Deploy
        run: |-
          kubectl set image deployment/${{env.DEPLOYMENT_NAME}} ${{env.CONTAINER_NAME}}=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl -n development rollout status deployment/${{env.DEPLOYMENT_NAME}}
          kubectl -n development get services -o wide
